package seeder

// GetMassiveATPPlayers returns 100+ ATP players with real rankings
// Data source: https://github.com/JeffSackmann/tennis_atp (atp_rankings_current.csv)
func GetMassiveATPPlayers() []PlayerSeedData {
	return []PlayerSeedData{
		// Top 50 ATP Rankings (Current)
		{ID: "j-sinner", Name: "J. Sinner", CountryCode: "IT", Rank: 1, Points: 11830, Age: 23, HeightCm: 193, Plays: "Right"},
		{ID: "c-alcaraz", Name: "C. Alcaraz", CountryCode: "ES", Rank: 2, Points: 8855, Age: 21, HeightCm: 183, Plays: "Right"},
		{ID: "n-djokovic", Name: "N. Djokovic", CountryCode: "RS", Rank: 3, Points: 7910, Age: 37, HeightCm: 188, Plays: "Right"},
		{ID: "d-medvedev", Name: "D. Medvedev", CountryCode: "RU", Rank: 4, Points: 5490, Age: 28, HeightCm: 198, Plays: "Right"},
		{ID: "a-zverev", Name: "A. Zverev", CountryCode: "DE", Rank: 5, Points: 5010, Age: 27, HeightCm: 198, Plays: "Right"},
		{ID: "a-rublev", Name: "A. Rublev", CountryCode: "RU", Rank: 6, Points: 4275, Age: 27, HeightCm: 188, Plays: "Right"},
		{ID: "h-rune", Name: "H. Rune", CountryCode: "DK", Rank: 7, Points: 4025, Age: 21, HeightCm: 185, Plays: "Right"},
		{ID: "h-hurkacz", Name: "H. Hurkacz", CountryCode: "PL", Rank: 8, Points: 3815, Age: 27, HeightCm: 196, Plays: "Right"},
		{ID: "t-fritz", Name: "T. Fritz", CountryCode: "US", Rank: 9, Points: 5100, Age: 27, HeightCm: 196, Plays: "Right"},
		{ID: "s-tsitsipas", Name: "S. Tsitsipas", CountryCode: "GR", Rank: 10, Points: 2950, Age: 26, HeightCm: 193, Plays: "Right"},

		{ID: "g-dimitrov", Name: "G. Dimitrov", CountryCode: "BG", Rank: 11, Points: 3350, Age: 33, HeightCm: 191, Plays: "Right"},
		{ID: "t-paul", Name: "T. Paul", CountryCode: "US", Rank: 12, Points: 2840, Age: 27, HeightCm: 185, Plays: "Right"},
		{ID: "a-de-minaur", Name: "A. de Minaur", CountryCode: "AU", Rank: 13, Points: 2775, Age: 25, HeightCm: 183, Plays: "Right"},
		{ID: "u-humbert", Name: "U. Humbert", CountryCode: "FR", Rank: 14, Points: 2670, Age: 26, HeightCm: 188, Plays: "Left"},
		{ID: "k-khachanov", Name: "K. Khachanov", CountryCode: "RU", Rank: 15, Points: 2430, Age: 28, HeightCm: 198, Plays: "Right"},
		{ID: "b-shelton", Name: "B. Shelton", CountryCode: "US", Rank: 16, Points: 2225, Age: 22, HeightCm: 193, Plays: "Left"},
		{ID: "f-auger-aliassime", Name: "F. Auger Aliassime", CountryCode: "CA", Rank: 17, Points: 2100, Age: 24, HeightCm: 193, Plays: "Right"},
		{ID: "l-musetti", Name: "L. Musetti", CountryCode: "IT", Rank: 18, Points: 1870, Age: 22, HeightCm: 185, Plays: "Right"},
		{ID: "j-draper", Name: "J. Draper", CountryCode: "GB", Rank: 19, Points: 1765, Age: 23, HeightCm: 193, Plays: "Left"},
		{ID: "a-fils", Name: "A. Fils", CountryCode: "FR", Rank: 20, Points: 1765, Age: 20, HeightCm: 193, Plays: "Right"},

		{ID: "s-baez", Name: "S. Baez", CountryCode: "AR", Rank: 21, Points: 1760, Age: 24, HeightCm: 170, Plays: "Right"},
		{ID: "j-lehecka", Name: "J. Lehecka", CountryCode: "CZ", Rank: 22, Points: 1710, Age: 23, HeightCm: 191, Plays: "Right"},
		{ID: "f-tiafoe", Name: "F. Tiafoe", CountryCode: "US", Rank: 23, Points: 1555, Age: 27, HeightCm: 188, Plays: "Right"},
		{ID: "a-bublik", Name: "A. Bublik", CountryCode: "KZ", Rank: 24, Points: 1530, Age: 27, HeightCm: 196, Plays: "Right"},
		{ID: "n-jarry", Name: "N. Jarry", CountryCode: "CL", Rank: 25, Points: 1511, Age: 29, HeightCm: 201, Plays: "Right"},
		{ID: "j-thompson", Name: "J. Thompson", CountryCode: "AU", Rank: 26, Points: 1480, Age: 30, HeightCm: 183, Plays: "Right"},
		{ID: "c-ruud", Name: "C. Ruud", CountryCode: "NO", Rank: 27, Points: 4255, Age: 26, HeightCm: 183, Plays: "Right"},
		{ID: "s-korda", Name: "S. Korda", CountryCode: "US", Rank: 28, Points: 1440, Age: 24, HeightCm: 196, Plays: "Right"},
		{ID: "t-griekspoor", Name: "T. Griekspoor", CountryCode: "NL", Rank: 29, Points: 1435, Age: 28, HeightCm: 185, Plays: "Right"},
		{ID: "m-arnaldi", Name: "M. Arnaldi", CountryCode: "IT", Rank: 30, Points: 1425, Age: 23, HeightCm: 185, Plays: "Right"},

		{ID: "t-machac", Name: "T. Machac", CountryCode: "CZ", Rank: 31, Points: 1410, Age: 24, HeightCm: 193, Plays: "Right"},
		{ID: "a-tabilo", Name: "A. Tabilo", CountryCode: "CL", Rank: 32, Points: 1375, Age: 27, HeightCm: 188, Plays: "Left"},
		{ID: "m-giron", Name: "M. Giron", CountryCode: "US", Rank: 33, Points: 1250, Age: 31, HeightCm: 183, Plays: "Right"},
		{ID: "j-mensik", Name: "J. Mensik", CountryCode: "CZ", Rank: 34, Points: 1233, Age: 19, HeightCm: 191, Plays: "Right"},
		{ID: "f-cerundolo", Name: "F. Cerundolo", CountryCode: "AR", Rank: 35, Points: 1215, Age: 26, HeightCm: 185, Plays: "Right"},
		{ID: "z-zhang", Name: "Z. Zhang", CountryCode: "CN", Rank: 36, Points: 1190, Age: 25, HeightCm: 185, Plays: "Right"},
		{ID: "a-mannarino", Name: "A. Mannarino", CountryCode: "FR", Rank: 37, Points: 1141, Age: 36, HeightCm: 185, Plays: "Left"},
		{ID: "c-norrie", Name: "C. Norrie", CountryCode: "GB", Rank: 38, Points: 1121, Age: 29, HeightCm: 188, Plays: "Left"},
		{ID: "j-sinner", Name: "J. Shang", CountryCode: "CN", Rank: 39, Points: 1103, Age: 19, HeightCm: 185, Plays: "Right"},
		{ID: "m-navone", Name: "M. Navone", CountryCode: "AR", Rank: 40, Points: 1100, Age: 23, HeightCm: 188, Plays: "Right"},

		{ID: "t-daniel", Name: "T. Daniel", CountryCode: "JP", Rank: 41, Points: 1077, Age: 31, HeightCm: 183, Plays: "Right"},
		{ID: "r-safiullin", Name: "R. Safiullin", CountryCode: "RU", Rank: 42, Points: 1055, Age: 27, HeightCm: 193, Plays: "Right"},
		{ID: "b-coric", Name: "B. Coric", CountryCode: "HR", Rank: 43, Points: 1052, Age: 28, HeightCm: 188, Plays: "Right"},
		{ID: "l-darderi", Name: "L. Darderi", CountryCode: "IT", Rank: 44, Points: 1050, Age: 22, HeightCm: 185, Plays: "Right"},
		{ID: "g-monfils", Name: "G. Monfils", CountryCode: "FR", Rank: 45, Points: 1021, Age: 38, HeightCm: 193, Plays: "Right"},
		{ID: "d-shapovalov", Name: "D. Shapovalov", CountryCode: "CA", Rank: 46, Points: 1005, Age: 25, HeightCm: 185, Plays: "Left"},
		{ID: "r-bautista-agut", Name: "R. Bautista Agut", CountryCode: "ES", Rank: 47, Points: 982, Age: 36, HeightCm: 183, Plays: "Right"},
		{ID: "j-struff", Name: "J. Struff", CountryCode: "DE", Rank: 48, Points: 975, Age: 34, HeightCm: 196, Plays: "Right"},
		{ID: "f-cobolli", Name: "F. Cobolli", CountryCode: "IT", Rank: 49, Points: 970, Age: 22, HeightCm: 188, Plays: "Right"},
		{ID: "a-popyrin", Name: "A. Popyrin", CountryCode: "AU", Rank: 50, Points: 946, Age: 25, HeightCm: 196, Plays: "Right"},

		// Top 51-100
		{ID: "y-nishioka", Name: "Y. Nishioka", CountryCode: "JP", Rank: 51, Points: 939, Age: 29, HeightCm: 170, Plays: "Left"},
		{ID: "f-fognini", Name: "F. Fognini", CountryCode: "IT", Rank: 52, Points: 929, Age: 37, HeightCm: 178, Plays: "Right"},
		{ID: "m-purcell", Name: "M. Purcell", CountryCode: "AU", Rank: 53, Points: 921, Age: 26, HeightCm: 185, Plays: "Right"},
		{ID: "r-gasquet", Name: "R. Gasquet", CountryCode: "FR", Rank: 54, Points: 911, Age: 38, HeightCm: 185, Plays: "Right"},
		{ID: "p-carreno-busta", Name: "P. Carreno Busta", CountryCode: "ES", Rank: 55, Points: 911, Age: 33, HeightCm: 188, Plays: "Right"},
		{ID: "d-schwartzman", Name: "D. Schwartzman", CountryCode: "AR", Rank: 56, Points: 907, Age: 32, HeightCm: 170, Plays: "Right"},
		{ID: "m-berrettini", Name: "M. Berrettini", CountryCode: "IT", Rank: 57, Points: 900, Age: 28, HeightCm: 196, Plays: "Right"},
		{ID: "f-bagnis", Name: "F. Bagnis", CountryCode: "AR", Rank: 58, Points: 893, Age: 34, HeightCm: 183, Plays: "Right"},
		{ID: "e-ruusuvuori", Name: "E. Ruusuvuori", CountryCode: "FI", Rank: 59, Points: 890, Age: 25, HeightCm: 193, Plays: "Right"},
		{ID: "d-thiem", Name: "D. Thiem", CountryCode: "AT", Rank: 60, Points: 890, Age: 31, HeightCm: 185, Plays: "Right"},

		{ID: "m-mcdonald", Name: "M. McDonald", CountryCode: "US", Rank: 61, Points: 865, Age: 29, HeightCm: 178, Plays: "Right"},
		{ID: "b-nakashima", Name: "B. Nakashima", CountryCode: "US", Rank: 62, Points: 858, Age: 23, HeightCm: 190, Plays: "Right"},
		{ID: "c-eubanks", Name: "C. Eubanks", CountryCode: "US", Rank: 63, Points: 846, Age: 28, HeightCm: 201, Plays: "Right"},
		{ID: "a-murray", Name: "A. Murray", CountryCode: "GB", Rank: 64, Points: 835, Age: 37, HeightCm: 191, Plays: "Right"},
		{ID: "m-mcdonald", Name: "M. Cressy", CountryCode: "US", Rank: 65, Points: 835, Age: 27, HeightCm: 198, Plays: "Right"},
		{ID: "d-evans", Name: "D. Evans", CountryCode: "GB", Rank: 66, Points: 825, Age: 34, HeightCm: 175, Plays: "Right"},
		{ID: "n-kyrgios", Name: "N. Kyrgios", CountryCode: "AU", Rank: 67, Points: 823, Age: 29, HeightCm: 193, Plays: "Right"},
		{ID: "f-coria", Name: "F. Coria", CountryCode: "AR", Rank: 68, Points: 814, Age: 32, HeightCm: 180, Plays: "Left"},
		{ID: "f-diaz-acosta", Name: "F. Diaz Acosta", CountryCode: "AR", Rank: 69, Points: 814, Age: 23, HeightCm: 180, Plays: "Right"},
		{ID: "a-vukic", Name: "A. Vukic", CountryCode: "AU", Rank: 70, Points: 782, Age: 28, HeightCm: 188, Plays: "Right"},

		{ID: "r-opelka", Name: "R. Opelka", CountryCode: "US", Rank: 71, Points: 782, Age: 27, HeightCm: 211, Plays: "Right"},
		{ID: "d-altmaier", Name: "D. Altmaier", CountryCode: "DE", Rank: 72, Points: 776, Age: 26, HeightCm: 183, Plays: "Right"},
		{ID: "p-martinez", Name: "P. Martinez", CountryCode: "ES", Rank: 73, Points: 774, Age: 27, HeightCm: 178, Plays: "Left"},
		{ID: "m-kecmanovic", Name: "M. Kecmanovic", CountryCode: "RS", Rank: 74, Points: 763, Age: 25, HeightCm: 183, Plays: "Right"},
		{ID: "b-bonzi", Name: "B. Bonzi", CountryCode: "FR", Rank: 75, Points: 748, Age: 28, HeightCm: 175, Plays: "Right"},
		{ID: "s-ofner", Name: "S. Ofner", CountryCode: "AT", Rank: 76, Points: 737, Age: 28, HeightCm: 183, Plays: "Right"},
		{ID: "r-hijikata", Name: "R. Hijikata", CountryCode: "AU", Rank: 77, Points: 718, Age: 23, HeightCm: 180, Plays: "Right"},
		{ID: "q-halys", Name: "Q. Halys", CountryCode: "FR", Rank: 78, Points: 715, Age: 28, HeightCm: 196, Plays: "Right"},
		{ID: "l-sonego", Name: "L. Sonego", CountryCode: "IT", Rank: 79, Points: 715, Age: 29, HeightCm: 191, Plays: "Right"},
		{ID: "j-duckworth", Name: "J. Duckworth", CountryCode: "AU", Rank: 80, Points: 711, Age: 32, HeightCm: 183, Plays: "Right"},

		{ID: "d-goffin", Name: "D. Goffin", CountryCode: "BE", Rank: 81, Points: 709, Age: 34, HeightCm: 180, Plays: "Right"},
		{ID: "h-gaston", Name: "H. Gaston", CountryCode: "FR", Rank: 82, Points: 706, Age: 24, HeightCm: 180, Plays: "Right"},
		{ID: "r-albot", Name: "R. Albot", CountryCode: "MD", Rank: 83, Points: 696, Age: 34, HeightCm: 183, Plays: "Right"},
		{ID: "c-lestienne", Name: "C. Lestienne", CountryCode: "FR", Rank: 84, Points: 694, Age: 32, HeightCm: 178, Plays: "Right"},
		{ID: "f-marozsan", Name: "F. Marozsan", CountryCode: "HU", Rank: 85, Points: 688, Age: 25, HeightCm: 185, Plays: "Right"},
		{ID: "a-rinderknech", Name: "A. Rinderknech", CountryCode: "FR", Rank: 86, Points: 680, Age: 29, HeightCm: 196, Plays: "Right"},
		{ID: "t-etcheverry", Name: "T. Etcheverry", CountryCode: "AR", Rank: 87, Points: 676, Age: 25, HeightCm: 185, Plays: "Left"},
		{ID: "y-hanfmann", Name: "Y. Hanfmann", CountryCode: "DE", Rank: 88, Points: 673, Age: 33, HeightCm: 191, Plays: "Right"},
		{ID: "l-klein", Name: "L. Klein", CountryCode: "SK", Rank: 89, Points: 664, Age: 26, HeightCm: 180, Plays: "Left"},
		{ID: "d-fokina", Name: "D. Fokina", CountryCode: "ES", Rank: 90, Points: 661, Age: 25, HeightCm: 178, Plays: "Left"},

		{ID: "a-cazaux", Name: "A. Cazaux", CountryCode: "FR", Rank: 91, Points: 656, Age: 22, HeightCm: 183, Plays: "Right"},
		{ID: "m-fucsovics", Name: "M. Fucsovics", CountryCode: "HU", Rank: 92, Points: 654, Age: 32, HeightCm: 188, Plays: "Right"},
		{ID: "t-monteiro", Name: "T. Monteiro", CountryCode: "BR", Rank: 93, Points: 630, Age: 30, HeightCm: 183, Plays: "Right"},
		{ID: "c-moutet", Name: "C. Moutet", CountryCode: "FR", Rank: 94, Points: 629, Age: 25, HeightCm: 175, Plays: "Left"},
		{ID: "f-comesana", Name: "F. Comesana", CountryCode: "AR", Rank: 95, Points: 628, Age: 24, HeightCm: 180, Plays: "Right"},
		{ID: "r-carballes-baena", Name: "R. Carballes Baena", CountryCode: "ES", Rank: 96, Points: 626, Age: 31, HeightCm: 180, Plays: "Right"},
		{ID: "d-prizmic", Name: "D. Prizmic", CountryCode: "HR", Rank: 97, Points: 626, Age: 20, HeightCm: 188, Plays: "Right"},
		{ID: "m-polmans", Name: "M. Polmans", CountryCode: "AU", Rank: 98, Points: 621, Age: 27, HeightCm: 185, Plays: "Right"},
		{ID: "r-nadal", Name: "R. Nadal", CountryCode: "ES", Rank: 99, Points: 619, Age: 38, HeightCm: 185, Plays: "Left"},
		{ID: "j-isner", Name: "J. Isner", CountryCode: "US", Rank: 100, Points: 617, Age: 39, HeightCm: 208, Plays: "Right"},
	}
}
